<?php
/**
 * @var $block \Xigen\MarkerIo\Block\Snippet
 * phpcs:disable Generic.Files.LineLength
 */
$viewModel = $block->getData('viewModel');
?>
<script>
window.markerConfig = {
    destination: '<?= $block->escapeJs($viewModel->getDestination()) ?>',
};
</script>
<script>
!function(e,r,t){if(e.__Marker)return;e.__Marker={};var n=r.createElement("script");n.async=1,n.src="https://edge.marker.io/latest/shim.js";var s=r.getElementsByTagName("script")[0];s.parentNode.insertBefore(n,s)}(window,document);
</script>